baseURL = "https://delusionaloptimist.github.io/"
defaultContentLanguage = "en"
languageCode = "en"

title = "DelusionalOptimist"

theme = "gokarna"

enableEmoji = true
enableRobotsTXT = true

[params]
  title = "Hey! I'm Rudraksh."
  subtitle = "I also go by DelusionalOptimist across the interwebs : )"
	avatarURL = "/rudraksh-pareek.jpg"
  footer = "Rudraksh Pareek"
  socialIcons = [
    {name = "github", url = "https://github.com/DelusionalOptimist/"},
    {name = "twitter", url = "https://twitter.com/Del_Optimist/"},
    {name = "linkedin", url = "https://linkedin.com/in/rudraksh-pareek/"},
  ]
  showPostsOnHomePage = "popular"
  metaKeywords = ["blog"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "Resume"
    url = "https://drive.google.com/file/d/1IS6nEOysnhUEo24BhjpgezTzi0Fz6xCP/view"
    weight = 3

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 5

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/DelusionalOptimist"
    weight = 6

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7
